apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quizzes
  labels:
    app: quizzes
spec:
  template:
    metadata:
      labels:
        app: quizzes
    spec:
      containers:
        - name: quizzes
          image: gcr.io/[PROJECT_ID]/quizzes
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: dbname
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.15
          # Replace <INSTANCE_CONNECTION_NAME> with your instances connection name!
          command: ["/cloud_sql_proxy",
                    "-instances=<INSTANCE_CONNECTION_NAME>=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: my-secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: my-secrets-volume
          secret:
            secretName: csql-proxy-acct